### ISSUE TITLE
Collect the list of partners as per category

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#17]
There is the possibility of displaying the partners and collaboration logo somewhere on the website, so for that, I need to collect past and present the partners' name and their websites.

### Acceptance Criteria

- [ ] I have the list of partners on the working sheet.

### Tasks

- [ ] Go through the provided docs.
- [ ] Collect the name and website of all partners.

### Working Sheet

- https://docs.google.com/spreadsheets/d/1bh7lGqy7G6DIgyPZZuLBooMvnwrGzfJm6St1PkAnGPU/edit?usp=sharing
