### ISSUE TITLE
Put new domain (wisteamnepal.org) under maintenance

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#18]
Since we are going live in the new domain, it will be a better idea to put the new domain under maintenance and connect it with the Azure server so that we don't have to request the domain provider later.

### Tasks Details

- [ ] Create Azure instance for the new domain.
- [ ] Provide the IP details to the team.
- [ ] Ask the domain provider (probably Himalayan Host) to update the details in the new domian.

**Comment by arjun-gautam** [comment]
@nikeshbalami couldn't create the ubuntu web server. I am unable to allocate resource.

**Comment by arjun-gautam** [comment]
Closing for server not available now.
