### ISSUE TITLE
Collect reference website

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#2]
To effectively understand the perspective of the WiSTEAM team and to gather the inspiration for the designer to get started; collect a few reference websites for both - organization and LMS.

### Acceptance Criteria

- [x] I now have a list of few reference websites in the working docs.

### Tasks Details

- [x] Search and collect the reference from online sources.
- [x] Go through the relevant partners' websites.
- [x] Ask for the WiSTEAM staff the submit the website, which they like most.
- [x] Compile all the lists in the working docs.

### Working Docs

- https://docs.google.com/document/d/1swqSDAfT6VfuHy0KE__rD7EtwQYeiTsXPCo8Gx68bhw/edit?usp=sharing

**Comment by nikeshbalami** [comment]
**CLOSING** the issue, since we now have enough inspiration to start the mockup. Figma has been started.
