### ISSUE TITLE
Update and create multiple Figma design for Homepage incorporating the feedback of the WiSTEAM team

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#22]
In the last meeting, WiSTEAM provided feedback on the first draft of the homepage design, which needs to be incorporated.

### Acceptance Criteria

- [x] I now have multiple Homepage designs, which the team can look at and make a selection.

### Tasks

- [x] Work with the design team and share the details of the feedbacks
- [x] Go through the map concepts
- [x] Create multiple Figma design and test the various concept

- **Figma link:** https://www.figma.com/file/rEnp3VTnzAprgu17UYnX15/WiSTEAM-Website?node-id=0%3A1

**Comment by nikeshbalami** [comment]
Multiple Figma design has been created and tested incorporating all needed features.
