### ISSUE TITLE
Collect reference website which has a map function

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#23]
The map features have been marked mandatory for the homepage, so for that, I need to collect some reference websites which we can visit for inspiration.

### Acceptance Criteria

- [x] I now have a couple of websites on the list, which I can show to the team during the discussion.

### Tasks

- [x] Search and go through the national website, which has displayed data of impact on the map of Nepal.
- [x] Collect the URL and screenshot in the docs.

**Comment by nikeshbalami** [comment]
Have collected the reference website with Maps in this docs: https://docs.google.com/document/d/1swqSDAfT6VfuHy0KE__rD7EtwQYeiTsXPCo8Gx68bhw/edit?usp=sharing
