### ISSUE TITLE
Review and finalize the Homepage Figma design

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#24]
Based on the suggestion, the Homepage design has been updated.

### Acceptance Criteria

- [ ] I have reviewed the homepage design with the WiSTEAM team.

### Tasks

- [ ] Schedule a meeting with the WiSTEAM team.
- [ ] Review the design.
- [ ] Collect any extra feedback and finalize the concept.
- [ ] Communicate the message the development team.
