### ISSUE TITLE
Collect resource page requirements and develop Figma design

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#25]
To publish the resources developed, I need to create a separate page where users can publish the resources.

### Acceptance Criteria

- [x] I have collected the page requirement for the resources page.
- [x] I have developed the design for the resource page.

### Tasks

- [x] Review the existing documents and collect the page requirements.
- [x] Review the page requirement with the WiSTEAM team.
- [x] Develop the design accordingly.

### Working Docs

- Requirement docs: https://docs.google.com/spreadsheets/d/1qNOVpqoeXxSrWfSaVJ36mEjGZxQ8esS02BJdnipPr6M/edit?usp=sharing
- Figma: 
- https://www.figma.com/file/rEnp3VTnzAprgu17UYnX15/WiSTEAM-Website

**Comment by nikeshbalami** [comment]
The design of the resource page has been **completed**.
