### ISSUE TITLE
Collect project page requirements and develop Figma design

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#26]
To publish the details of the projects, I need to create a separate page where users can publish the project details.

### Acceptance Criteria

- [x] I have collected the page requirement for the project page.
- [x] I have developed the design for the project page.

### Tasks

- [x] Review the existing documents and collected the page requirements.
- [x] Review the page requirement with the WiSTEAM team.
- [x] Develop the design accordingly.

### Working Docs

- Requirement docs: https://docs.google.com/spreadsheets/d/1qNOVpqoeXxSrWfSaVJ36mEjGZxQ8esS02BJdnipPr6M/edit?usp=sharing
- Figma: 
- https://www.figma.com/file/rEnp3VTnzAprgu17UYnX15/WiSTEAM-Website

**Comment by nikeshbalami** [comment]
The project page layout design has been **completed**.
