### ISSUE TITLE
Collect impact stories page requirements and develop Figma design

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#27]
To publish the impact stories, I need to create a separate page where users can publish the details of the impact stories created similar to the blog post.

### Acceptance Criteria

- [x] I have collected the page requirement for the impact stories page.
- [x] I have developed the design for the impact stories page.

### Tasks

- [x] Review the existing documents and collected the page requirements.
- [x] Review the page requirement with the WiSTEAM team.
- [x] Develop the design accordingly.

### Working Docs

- Requirement docs: https://docs.google.com/spreadsheets/d/1qNOVpqoeXxSrWfSaVJ36mEjGZxQ8esS02BJdnipPr6M/edit?usp=sharing
- Figma: 
- https://www.figma.com/file/rEnp3VTnzAprgu17UYnX15/WiSTEAM-Website

**Comment by nikeshbalami** [comment]
The design of the impact stories layout has been **completed**.
