### ISSUE TITLE
Collect about us page requirements and develop Figma design

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#29]
To display the mission, vision, objectives, team, partners details of the organization, I need a separate about us page with required dropdown menus.

### Acceptance Criteria

- [x] I have collected the page requirement for the about us page with required dropdown details.
- [x] I have developed the design for the donate page.

### Tasks

- [x] Review the existing documents and collect the page requirements.
- [x] Review the page requirement with the WiSTEAM team.
- [x] Develop the design accordingly.

### Working Docs

- Requirement docs: https://docs.google.com/spreadsheets/d/1qNOVpqoeXxSrWfSaVJ36mEjGZxQ8esS02BJdnipPr6M/edit?usp=sharing
- Figma: 
- https://www.figma.com/file/rEnp3VTnzAprgu17UYnX15/WiSTEAM-Website

**Comment by nikeshbalami** [comment]
Desing of the About page is **completed**.
