### ISSUE TITLE
Finalize page requirement and template mapping

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#3]
For the designer and developer to understand what types of pages they need to develop; they required the list of page requirements.

### Acceptance Criteria

- [x] I now have the details of the page requirement ready in the working sheet.

### Task Details

- [x] Go through the old documents created by Binita.
- [x] Review the staff consultation document.
- [x] List the required page details in the working sheet.
- [x] Discuss and finalize the collected page details with the team.

### Working Sheet

- https://docs.google.com/spreadsheets/d/1qNOVpqoeXxSrWfSaVJ36mEjGZxQ8esS02BJdnipPr6M/edit?usp=sharing

**Comment by nikeshbalami** [comment]
The collection of the Homepage requirement is **DONE**. Breaking down requirements as per page in various issues, to reduce complexity.
