### ISSUE TITLE
Revise the Homepage requirement sheet

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#30]
The existing homepage requirement was created based on the concept gathered from the old document and it seems the details included in the old documents are not all relevant. So to reduce the complexity, revise the homepage requirement sheet as per the current Figma design.

### Acceptance Criteria

- [x] I now have an updated homepage requirement sheet, which shows what types of details will be shown on the website homepage.

### Tasks

- [x] Update the sheet as per the Figma design.
- [x] Review the sheet with WiSTEAM team and make sure all the features which they want are covered.
- [x] Finalize the requirement sheet, with no further changes.

**Comment by nikeshbalami** [comment]
All the tentative featured required for the homepage has been documented and covered.
