### ISSUE TITLE
Review the reference website and finalize the types of function that we want to have

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#31]
Currently, the map function has been added to the Figma homepage design to demonstrate the impact acres. The concept is similar to the COVID website and Explore Bhaktapur. Now, I need to review the concept with the WiSTEAM team to discuss how they want the map to function when clicked.

### Acceptance Criteria

- [x] I have reviewed the reference website with the WiSTEAM team, and finalize the type of function they want to have.

### Tasks

- [x] Schedule a meeting with the WiSTEAM team.
- [x] Review and finalize the type of function.

- Reference website docs: https://docs.google.com/document/d/1swqSDAfT6VfuHy0KE__rD7EtwQYeiTsXPCo8Gx68bhw/edit

**Comment by nikeshbalami** [comment]
The reference website has been reviewed, and the type of map function which the team wants to have has been discussed and finalized.
