### ISSUE TITLE
Create a Netify instance of the project from Github

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#32]
For the stagging site, we are shifting from Heruko to Netify.

### Acceptance Criteria

- [x] I now have the stagging site ready at Netify.

### Tasks

- [x] Create a Netify project
- [x] Link project to Github
- [x] Share the link to the team members

**Comment by CodeDreamerSLS** [comment]
https://wistemnepal.netlify.app/
