### ISSUE TITLE
Collect Jobs page requirements and develop Figma design

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#33]
To publish the notice of the vacancy, I need to create a jobs page, where the link of the current opening will be displayed.

### Acceptance Criteria

- [ ] I have collected the page requirement for the jobs page.
- [ ] I have developed the design for the jobs page.

### Tasks

- [ ] Review the reference website and collect requirements.
- [ ] Review the page requirement with the WiSTEAM team.
- [ ] Develop the design accordingly.

### Working Docs

- Requirement docs: https://docs.google.com/spreadsheets/d/1qNOVpqoeXxSrWfSaVJ36mEjGZxQ8esS02BJdnipPr6M/edit?usp=sharing
- Figma:
- https://www.figma.com/file/rEnp3VTnzAprgu17UYnX15/WiSTEAM-Website

**Comment by arjun-gautam** [comment]
@nikeshbalami, are there any references, I can start with?

**Comment by nikeshbalami** [comment]
Something like this @arjun-gautam - https://accessnow.bamboohr.com/jobs/

**Comment by arjun-gautam** [comment]
@nikeshbalami the design is complete. Please review the figma and you may close the issue
