### ISSUE TITLE
Update the page requirement sheet of all website pages

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#34]
The current requirement sheet hasn't been properly updated as per the design. So, to remove the confusion, I need to update the page requirement sheet of all pages and map the function accordingly.

### Acceptance Criteria

- [x] I now have the updated sheet with proper details.

### Tasks

- [x] Review all the new features added to the design.
- [x] Add the features to the requirement sheet.

Requirement Sheet: https://docs.google.com/spreadsheets/d/1qNOVpqoeXxSrWfSaVJ36mEjGZxQ8esS02BJdnipPr6M/edit?usp=sharing

**Comment by nikeshbalami** [comment]
All the requirements details have been ### updated in the sheet.
