### ISSUE TITLE
Collect the impact components to be shown in the Homepage Impact Area

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#35]
Currently, 4 of the major indicators have been shown on the homepage. WiSTEAM team has commented saying the possibility of displaying 6 - 8 components.

### Acceptance Criteria

- [x] I have discussed with the team and collected the possible components.

### Tasks

- [x] Discuss with the team regarding types of impact components that they have been thinking about.
- [x] Document the components and see if that component fits for all projects.
- [x] Finalize the list of impact components.

Working sheet: https://docs.google.com/spreadsheets/d/1fnciCBRvJ8XPPxbqKEFyoujJPrryY7hs6dKeudGGoyA/edit?usp=sharing

**Comment by nikeshbalami** [comment]
The impact components have been **collected**.
