### ISSUE TITLE
Design homepage banner

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#36]
A static homepage banner needs to be designed so that it can replace the existing dummy banner.

### Acceptance Criteria

- [ ] I now have the banner ready.

### Tasks

- [ ] Ask the WiSTEAM designer to create a banner.
- [ ] Collect the banner design and send it to the development team.

**Comment by arjun-gautam** [comment]
@nikeshbalami @WiSTEAM2016 Is this still on progress?
