### ISSUE TITLE
Collect the reference LMS and Elearning website

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#37]
Before getting started with the requirement gathering, I need to collect and go through the various others LMS and learning websites to gather tentative ideas.

### Acceptance Criteria

- [ ] I have collected a few national and international LMS links.

### Tasks

- [ ] Google searches and explores various LMS links and functions.
- [ ] Collect the URL of suitable LMS in the working docs.

Reference website: https://docs.google.com/document/d/1swqSDAfT6VfuHy0KE__rD7EtwQYeiTsXPCo8Gx68bhw/edit?usp=sharing
