### ISSUE TITLE
Explore the Neema Academy dashboard/backend

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#38]
I have the login credentials - use the credential to explore the Neema Academy dashboard / backed and collect the details of the potential features.

### Acceptance Criteria

- [ ] I have explored the Neema Academy backend and collected the reference for the potential features.

### Tasks

- [ ] Use the credentials to log in.
- [ ] Explore the features in detail.
- [ ] Collect and document the potential features.
