### ISSUE TITLE
Resolve all the comments of page design

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#39]
Currently, we have around 23 comments on the design of the various website pages, which need to be resolved.

### Acceptance Criteria

- [x] I have resolved all the comments and have made all necessary changes.

### Tasks

- [x] Schedule a team meeting and go through the comments.
- [x] Make the necessary changes and resolve the comments.
- [x] Finalize the design and submit it to the development team.

**Comment by nikeshbalami** [comment]
All the relevant comments have been **resolved and incorporated**. Some comments were unrelevent.
