### ISSUE TITLE
Collect branding details

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#4]
To get started with the design brainstorming, we need the collect the details of the existing branding details of the organization.

### Acceptance Criteria

- [x] I now have all the details regarding the branding guideline in the working folder.

### Tasks Details

- [x] Reach out to the WiSTEAM team requesting the details of the fonts, color and use of a logo.
- [x] Collect all the existing branding details.
- [x] Compile the details in the working folder and share them with a developer team.

### Working Folder

- https://drive.google.com/drive/folders/1cardcGVecOPATTi3E_UzMSibEy3vlR9D?usp=sharing

**Comment by nikeshbalami** [comment]
**CLOSING** the issues. We now the branding details in our working folder.
