### ISSUE TITLE
Start Page Requirement and Template Mapping sheet for STEAM शिक्षा LMS

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#40]
To get started with the concept and design of the STEAM शिक्षा LMS, I need to start and prepare what kinds of page requirements are required and map its template accordingly.

### Acceptance Criteria

- [ ] I have the page requirements and template mapping sheet ready for STEAM शिक्षा.

### Tasks

- [ ] Go through the reference website and relevant site.
- [ ] Prepare the initial draft of the page requirements.
- [ ] Schedule a meeting with the WiSTEAM team.
- [ ] Update the sheet as per the meeting discussion.
- [ ] Finalize the sheet and handover it to the development team.

Working sheet: https://docs.google.com/spreadsheets/d/1EIWQ8ltbT2BZD9FOwBQEU7805TqMRYSeI-HmKvm3Iuw/edit?usp=sharing
