### ISSUE TITLE
Collect data of map compenents in the main sheet

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#41]
To display the data in the map, I need to collect the data into the sheet so that the developer team can use it to create the visualization.

### Acceptance Criteria

- [x] I now have details in the sheet.

### Tasks

- [x] Create a master sheet to collect the data.
- [x] Share the sheet with the WiSTEAM team.
- [x] Collect the data.

- Master Sheet: https://docs.google.com/spreadsheets/d/1fnciCBRvJ8XPPxbqKEFyoujJPrryY7hs6dKeudGGoyA/edit?usp=sharing

**Comment by nikeshbalami** [comment]
All the required data has been **collected**.
