### ISSUE TITLE
Start a figma project for the website layout

### ISSUE THREAD

**Issue by arjun-gautam** [wisteamnepal/wisteam-web#5]
### Task Details

- [x] Go through the page requirement docs.
- [x] Start the Figma team and invite everyone.
- [x] Create homepage design as per requirement.

**Comment by arjun-gautam** [comment]
Inspirations note: https://docs.google.com/document/d/1swqSDAfT6VfuHy0KE__rD7EtwQYeiTsXPCo8Gx68bhw/edit

**Comment by arjun-gautam** [comment]
Page requirements note: https://docs.google.com/spreadsheets/d/1qNOVpqoeXxSrWfSaVJ36mEjGZxQ8esS02BJdnipPr6M/edit#gid=0

**Comment by nikeshbalami** [comment]
Just updated the homepage page details as per our morning discussion. Will collect the requirements for the others page.
