### ISSUE TITLE
Develop Code of Conduct and Privacy Policy page

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#67]
To share the basic guidelines regarding the code of conduct and privacy policy,  we need a page that can be navigated via the Homepage footer.

### Acceptance Criteria

- [x] I have the Code of Conduct page.
- [x] I have the Privacy Policy page.

### Tasks

- [x] Make a change in the design and add page details
- [x] Implement the change in Backend and the Frontend both.

**Comment by arjun-gautam** [comment]
@CodeDreamerSLS There is a new page added at the bottom of figma design. Please develop this page also. For now just added the Lorem Ipsum text. Content will be added later.

**Comment by CodeDreamerSLS** [comment]
> @CodeDreamerSLS There is a new page added at the bottom of figma design. Please develop this page also. For now just added the Lorem Ipsum text. Content will be added later.

Done added COC page & privacy policy page..Delay occured as rt. now internet is gone & commited using data
