### ISSUE TITLE
Create STEAM शिक्षा LMS user flow diagram

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#68]
To understand the content and user flow, I need to create a diagram so that it will be easier for the development team.

### Acceptance Criteria

- [ ] I have created the user flow diagram and share it with the team.

### Tasks

- [ ] Collect the page requiremnts
- [ ] Review the existing documents
- [ ] Create the user flow diagram
