### ISSUE TITLE
Collect old and existing project details

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#7]
For the project page, we need to collect the details of all the old and existing project details.

### Acceptance Criteria

- [ ] I have the project details collected in the working sheet.

### Task Details

- [ ] Sit with Binita and the team to review all the project details
- [ ] Document the details in the working sheet.

### Working Sheet

- https://docs.google.com/spreadsheets/d/14i6-tDCqTA42Bc604yK3RhyxiYTnHb6k8d45Of-4ADc/edit?usp=sharing
