### ISSUE TITLE
Collect useful cover/image reference that can be used in website

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#8]
### Acceptance Criteria

- [x] I have a few images in the working folder (if possible by the WiSTEAM team)

### Tasks Details

- [x] Work with the WiSTEAM team to collect the image which they clicked during projects.
- [x] Upload the reference in the folder.

### Working Folder

- https://drive.google.com/drive/folders/1SEvSyakttFjY04iAWNkhnXqY5qWkPKsB?usp=sharing

**Comment by nikeshbalami** [comment]
The reference images have been **collected**.
