### ISSUE TITLE
Collect team details and photos

### ISSUE THREAD

**Issue by nikeshbalami** [wisteamnepal/wisteam-web#9]
For the team page, we need the details of a team like headshot photos and bio with relevant links.

### Acceptance Criteria

- [ ] I have collected all the information in the working folder

### Task Details

- [ ] Reach out to the team and staff via Slack and ask for the details.
- [ ] Curate the details in the working folder

### Working Folder

- https://drive.google.com/drive/folders/1Ly4-Dko6yPzoOrCBNJa9gkq4Merit3w8?usp=sharing
